cl.scm will hold all OpenCL apps in GNU Guix.
Commit directly under /gnu/packages
Secondly, seek build advice from the pocl developers. At the moment, pocl fails to build.

Error encountered:

common.c: In function ?llvm_codegen?:
common.c:110:13: error: ?CLANGXX? undeclared (first use in this function)
             CLANGXX " " HOST_CLANG_FLAGS " " HOST_LD_FLAGS " -o %s %s",
             ^
common.c:110:13: note: each undeclared identifier is reported only once for each function it appears in
common.c:110:21: error: expected ?)? before string constant
             CLANGXX " " HOST_CLANG_FLAGS " " HOST_LD_FLAGS " -o %s %s",
                     ^
Makefile:608: recipe for target 'libpocl_devices_la-common.lo' failed
make[6]: *** [libpocl_devices_la-common.lo] Error 1
make[6]: *** Waiting for unfinished jobs....

Investigations identify the following shortfalls:

1. We need to port LLVM 3.8 (and clang) to GNU Guix properly.
2. We will also need to use substitutes to work around the cmake installation trying to write directly to /etc/OpenCL/vendors. This must be done the guix way.